
trigger:
- main

pool: 
  name: 'Default'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: PublishBuildArtifacts@1
 inputs:
   PathtoPublish: 'out'
   ArtifactName: 'drop'
   publishLocation: 'Container'
